In [1]:
import pandas as pd
epidemiology = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/epidemiology.csv")
demographics = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/demographics.csv")
economy = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/economy.csv")
emergency_declaration = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/lawatlas-emergency-declarations.csv")
geography = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/geography.csv")
health = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/health.csv")
hospitalization = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/hospitalizations.csv")
mobility = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/mobility.csv")
search_trends = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/google-search-trends.csv")
vaccination = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/vaccinations.csv")
government_response = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/oxford-government-response.csv")
world_bank = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/worldbank.csv")
epi_by_age = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/by-age.csv")
epi_by_sex = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/by-sex.csv")
key = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/index.csv")

/tmp/ipykernel_99940/1509223055.py:14: DtypeWarning: Columns (148,149,150,151) have mixed types. Specify dtype option on import or set low_memory=False.
  epi_by_age = pd.read_csv("https://storage.googleapis.com/covid19-open-data/v3/by-age.csv")

In [2]:
tables = [epidemiology, demographics, economy, emergency_declaration, geography, health, hospitalization, mobility, search_trends, vaccination,
        government_response, world_bank, epi_by_age, epi_by_sex, key]

In [3]:
def get_df_name(df):
    name =[x for x in globals() if globals()[x] is df][0]
    return name

for table in tables:
  print(get_df_name(table), table.shape)

epidemiology (12525825, 10)
demographics (21689, 19)
economy (404, 4)
emergency_declaration (8364, 104)
geography (22130, 8)
health (3504, 14)
hospitalization (1768485, 11)
mobility (6321226, 8)
search_trends (2713929, 424)
vaccination (2545118, 32)
government_response (303969, 22)
world_bank (215, 1405)
epi_by_age (3822577, 152)
epi_by_sex (3848340, 30)
key (22963, 15)

These datasets can be aggregated to make a table that is larger than 100,000 rows $\times$ 50 columns. These datasets have the common `location_key` and  `date`. An example is printed out.

In [29]:
# a function to see how many columns in each table is missing >20% of the data
def find_20_miss(df):
    missing_by_cln = df.isna().sum()
    percent_missing_by_cln = missing_by_cln/(df.shape[0])
    return percent_missing_by_cln.loc[percent_missing_by_cln <= 0.2]

In [30]:
find_20_miss(epidemiology)

date                    0.000000
location_key            0.000079
new_confirmed           0.003994
new_deceased            0.068553
cumulative_confirmed    0.015870
cumulative_deceased     0.083907
dtype: float64

In [33]:
for table in tables:
    print(find_20_miss(table))

date                    0.000000
location_key            0.000079
new_confirmed           0.003994
new_deceased            0.068553
cumulative_confirmed    0.015870
cumulative_deceased     0.083907
dtype: float64
location_key         0.000046
population           0.001383
population_male      0.188206
population_female    0.188206
dtype: float64
location_key          0.002475
gdp_usd               0.076733
gdp_per_capita_usd    0.096535
dtype: float64
date                          0.0
location_key                  0.0
lawatlas_mitigation_policy    0.0
dtype: float64
location_key    0.000045
latitude        0.001446
longitude       0.001446
area_sq_km      0.122775
dtype: float64
location_key       0.000285
life_expectancy    0.001427
dtype: float64
date                                0.000000
location_key                        0.000000
new_hospitalized_patients           0.067478
cumulative_hospitalized_patients    0.069614
dtype: float64
date                   0.000000
location_key           0.000149
mobility_workplaces    0.019414
dtype: float64
date                       0.000000
location_key               0.000000
search_trends_infection    0.058982
search_trends_pain         0.002198
dtype: float64
date                                   0.000000
location_key                           0.000062
new_persons_fully_vaccinated           0.007721
cumulative_persons_fully_vaccinated    0.007331
dtype: float64
date                                 0.000000
location_key                         0.003013
school_closing                       0.005112
workplace_closing                    0.005678
cancel_public_events                 0.006254
restrictions_on_gatherings           0.006540
public_transport_closing             0.006988
stay_at_home_requirements            0.006234
restrictions_on_internal_movement    0.006366
international_travel_controls        0.012264
income_support                       0.055946
debt_relief                          0.056305
public_information_campaigns         0.006474
testing_policy                       0.011817
contact_tracing                      0.019045
facial_coverings                     0.007734
vaccination_policy                   0.008971
stringency_index                     0.007836
dtype: float64
location_key         0.004651
AG.LND.AGRI.K2       0.027907
AG.LND.AGRI.ZS       0.037209
AG.LND.ARBL.HA       0.041860
AG.LND.ARBL.HA.PC    0.051163
                       ...
TX.VAL.OTHR.ZS.WT    0.134884
TX.VAL.SERV.CD.WT    0.130233
TX.VAL.TRAN.ZS.WT    0.144186
TX.VAL.TRVL.ZS.WT    0.144186
VC.IDP.NWDS          0.139535
Length: 556, dtype: float64
date                          0.000000
location_key                  0.000000
new_confirmed_age_2           0.162354
new_confirmed_age_3           0.157371
new_confirmed_age_4           0.168878
new_confirmed_age_5           0.182116
cumulative_confirmed_age_0    0.053096
cumulative_confirmed_age_1    0.053096
cumulative_confirmed_age_2    0.053004
cumulative_confirmed_age_3    0.052960
cumulative_confirmed_age_4    0.052994
cumulative_confirmed_age_5    0.052994
cumulative_confirmed_age_6    0.117175
cumulative_confirmed_age_7    0.117577
cumulative_confirmed_age_8    0.118683
cumulative_confirmed_age_9    0.126621
age_bin_0                     0.000000
age_bin_1                     0.000000
age_bin_2                     0.000000
age_bin_3                     0.000000
age_bin_4                     0.000034
age_bin_5                     0.000266
age_bin_6                     0.065094
age_bin_7                     0.065773
age_bin_8                     0.067813
age_bin_9                     0.076705
dtype: float64
date                           0.000000
location_key                   0.000000
new_confirmed_male             0.113790
new_confirmed_female           0.115475
cumulative_confirmed_male      0.049094
cumulative_confirmed_female    0.049273
dtype: float64
location_key          0.000044
place_id              0.056700
wikidata_id           0.033924
country_code          0.000044
country_name          0.000000
subregion1_code       0.010800
subregion1_name       0.010756
subregion2_code       0.074468
subregion2_name       0.074468
iso_3166_1_alpha_2    0.000087
iso_3166_1_alpha_3    0.000044
aggregation_level     0.000000
dtype: float64

In [28]:
epidemiology.head()

,date,location_key,new_confirmed,new_deceased,new_recovered,new_tested,cumulative_confirmed,cumulative_deceased,cumulative_recovered,cumulative_tested
0,2020-01-01,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
1,2020-01-02,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
2,2020-01-03,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
3,2020-01-04,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN
4,2020-01-05,AD,0.0,0.0,NaN,NaN,0.0,0.0,NaN,NaN

In [9]:
vaccination.isna().sum()

date                                                   0
location_key                                         158
new_persons_vaccinated                           1612231
cumulative_persons_vaccinated                    1658214
new_persons_fully_vaccinated                       19651
cumulative_persons_fully_vaccinated                18658
new_vaccine_doses_administered                   1604390
cumulative_vaccine_doses_administered            1647958
new_persons_vaccinated_pfizer                    2533141
cumulative_persons_vaccinated_pfizer             2533141
new_persons_fully_vaccinated_pfizer              2502263
cumulative_persons_fully_vaccinated_pfizer       2502190
new_vaccine_doses_administered_pfizer            2514224
cumulative_vaccine_doses_administered_pfizer     2514167
new_persons_vaccinated_moderna                   2542814
cumulative_persons_vaccinated_moderna            2542814
new_persons_fully_vaccinated_moderna             2511936
cumulative_persons_fully_vaccinated_moderna      2511863
new_vaccine_doses_administered_moderna           2514224
cumulative_vaccine_doses_administered_moderna    2514167
new_persons_vaccinated_janssen                   2542814
cumulative_persons_vaccinated_janssen            2542814
new_persons_fully_vaccinated_janssen             2511936
cumulative_persons_fully_vaccinated_janssen      2511863
new_vaccine_doses_administered_janssen           2514224
cumulative_vaccine_doses_administered_janssen    2514167
new_persons_vaccinated_sinovac                   2535445
total_persons_vaccinated_sinovac                 2535445
new_persons_fully_vaccinated_sinovac             2545118
total_persons_fully_vaccinated_sinovac           2545118
new_vaccine_doses_administered_sinovac           2545118
total_vaccine_doses_administered_sinovac         2545118
dtype: int64

In [10]:
hospitalization.isna().sum()

date                                        0
location_key                                0
new_hospitalized_patients              119333
cumulative_hospitalized_patients       123111
current_hospitalized_patients         1584627
new_intensive_care_patients            620623
cumulative_intensive_care_patients     622435
current_intensive_care_patients       1576562
new_ventilator_patients               1757509
cumulative_ventilator_patients        1760209
current_ventilator_patients           1720617
dtype: int64

In [11]:
mobility.isna().sum()

date                                    0
location_key                          941
mobility_retail_and_recreation    2154446
mobility_grocery_and_pharmacy     2385316
mobility_parks                    3381539
mobility_transit_stations         3134225
mobility_workplaces                122718
mobility_residential              2192508
dtype: int64

In [13]:
government_response.isna().sum()

date                                       0
location_key                             916
school_closing                          1554
workplace_closing                       1726
cancel_public_events                    1901
restrictions_on_gatherings              1988
public_transport_closing                2124
stay_at_home_requirements               1895
restrictions_on_internal_movement       1935
international_travel_controls           3728
income_support                         17006
debt_relief                            17115
fiscal_measures                       157220
international_support                 157324
public_information_campaigns            1968
testing_policy                          3592
contact_tracing                         5789
emergency_investment_in_healthcare    152870
investment_in_vaccines                 71235
facial_coverings                        2351
vaccination_policy                      2727
stringency_index                        2382
dtype: int64

In [14]:
demographics.isna().sum()

location_key                       1
population                        30
population_male                 4082
population_female               4082
population_rural               21476
population_urban               21476
population_largest_city        21537
population_clustered           21568
population_density             20497
human_development_index        15951
population_age_00_09            4440
population_age_10_19            4441
population_age_20_29            4441
population_age_30_39            4433
population_age_40_49            4439
population_age_50_59            4457
population_age_60_69            4475
population_age_70_79            4562
population_age_80_and_older     4729
dtype: int64

In [16]:
world_bank.isna().sum()

location_key           1
AG.AGR.TRAC.NO       215
AG.CON.FERT.PT.ZS    135
AG.CON.FERT.ZS        51
AG.LND.AGRI.K2         6
                    ...
VC.IDP.TOCV          153
VC.IHR.PSRC.FE.P5    119
VC.IHR.PSRC.MA.P5    119
VC.IHR.PSRC.P5        80
VC.PKP.TOTL.UN       197
Length: 1405, dtype: int64

In [19]:
search_trends.head()

,date,location_key,search_trends_abdominal_obesity,search_trends_abdominal_pain,search_trends_acne,search_trends_actinic_keratosis,search_trends_acute_bronchitis,search_trends_adrenal_crisis,search_trends_ageusia,search_trends_alcoholism,...,search_trends_visual_acuity,search_trends_vomiting,search_trends_wart,search_trends_water_retention,search_trends_weakness,search_trends_weight_gain,search_trends_wheeze,search_trends_xeroderma,search_trends_xerostomia,search_trends_yawn
0,2020-01-01,AU,3.56,5.38,10.76,0.52,0.35,0.12,0.05,5.36,...,0.70,4.23,1.87,0.39,0.47,4.47,0.30,3.52,0.43,0.21
1,2020-01-02,AU,3.46,5.35,11.30,0.55,0.36,0.14,0.06,4.62,...,0.44,3.97,1.97,0.41,0.47,4.60,0.27,3.48,0.45,0.19
2,2020-01-03,AU,3.40,5.35,11.23,0.53,0.34,0.12,0.05,4.63,...,0.29,3.90,1.85,0.40,0.65,4.46,0.30,3.58,0.39,0.18
3,2020-01-04,AU,3.43,5.23,10.68,0.42,0.35,0.11,0.05,4.82,...,0.28,3.88,1.78,0.38,0.54,4.43,0.30,3.59,0.40,0.21
4,2020-01-05,AU,3.29,5.14,10.20,0.49,0.38,0.11,NaN,4.26,...,0.38,3.73,1.75,0.34,0.46,4.59,0.34,3.09,0.40,0.19