<a href="https://colab.research.google.com/github/danlingzhou16/stat390/blob/GraceZhu/STAT390_data_imputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
data = pd.read_csv("top_10_gdp_covid_data.csv")

<ipython-input-24-2a269cedd8f9>:2: DtypeWarning: Columns (38) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("top_10_gdp_covid_data.csv")

In [25]:
data.dtypes

Unnamed: 0             int64
date                  object
location_key_x        object
new_confirmed        float64
new_deceased         float64
                      ...
TX.VAL.MRCH.R5.ZS    float64
TX.VAL.MRCH.R6.ZS    float64
TX.VAL.MRCH.RS.ZS    float64
TX.VAL.MRCH.WL.CD    float64
TX.VAL.MRCH.XD.WD    float64
Length: 199, dtype: object

In [26]:
# This is the subset we are going to impute
num_data = data.select_dtypes(include='number')
num_data.dtypes

Unnamed: 0                int64
new_confirmed           float64
new_deceased            float64
cumulative_confirmed    float64
cumulative_deceased     float64
                         ...
TX.VAL.MRCH.R5.ZS       float64
TX.VAL.MRCH.R6.ZS       float64
TX.VAL.MRCH.RS.ZS       float64
TX.VAL.MRCH.WL.CD       float64
TX.VAL.MRCH.XD.WD       float64
Length: 187, dtype: object

In [27]:
# not going to be imputed
no_num = data.select_dtypes(include='object')
no_num.dtypes

date                  object
location_key_x        object
place_id              object
wikidata_id           object
country_code          object
country_name          object
subregion1_code       object
subregion1_name       object
iso_3166_1_alpha_2    object
iso_3166_1_alpha_3    object
location_key_y        object
location_key          object
dtype: object

In [28]:
# Danling -> checked missing value percentage in their original dataset
# Mingyi -> used the same method to check the missing value percentage after combining the dataset
# After this round of selection, all our columns will have <20% missing value
# Making sure dataset is ready for imputation
def find_20_miss(df):
    missing_by_cln = df.isna().sum()
    percent_missing_by_cln = missing_by_cln/(df.shape[0])
    return percent_missing_by_cln.loc[percent_missing_by_cln <= 0.2]

def select_20_miss(df):
    selected_cln = list(find_20_miss(df).index)
    return df[selected_cln]

In [29]:
num_data = select_20_miss(num_data)
# num_data = num_data.iloc[:,1:51]
num_data

,Unnamed: 0,new_confirmed,new_deceased,cumulative_confirmed,cumulative_deceased,population,population_male,population_female,latitude,longitude,...,TX.VAL.MRCH.OR.ZS,TX.VAL.MRCH.R1.ZS,TX.VAL.MRCH.R2.ZS,TX.VAL.MRCH.R3.ZS,TX.VAL.MRCH.R4.ZS,TX.VAL.MRCH.R5.ZS,TX.VAL.MRCH.R6.ZS,TX.VAL.MRCH.RS.ZS,TX.VAL.MRCH.WL.CD,TX.VAL.MRCH.XD.WD
0,9896188,0.0,0.0,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
1,9896189,0.0,0.0,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
2,9896190,0.0,0.0,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
3,9896191,0.0,0.0,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
4,9896192,0.0,0.0,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97179,494713,0.0,0.0,1139054.0,626.0,2656156.0,1120500.0,1111402.0,-26.0,121.0,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97180,494714,0.0,0.0,1139054.0,626.0,2656156.0,1120500.0,1111402.0,-26.0,121.0,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97181,494715,0.0,NaN,1139054.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97182,494716,0.0,NaN,1139054.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97183,494717,0.0,NaN,1139054.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005

In [30]:
# Drop the column that's highly correlated to the target variable, drop the repetitive column
num_data = num_data.drop(['cumulative_confirmed','cumulative_deceased'], axis=1)
num_data

,Unnamed: 0,new_confirmed,new_deceased,population,population_male,population_female,latitude,longitude,area_sq_km,life_expectancy,...,TX.VAL.MRCH.OR.ZS,TX.VAL.MRCH.R1.ZS,TX.VAL.MRCH.R2.ZS,TX.VAL.MRCH.R3.ZS,TX.VAL.MRCH.R4.ZS,TX.VAL.MRCH.R5.ZS,TX.VAL.MRCH.R6.ZS,TX.VAL.MRCH.RS.ZS,TX.VAL.MRCH.WL.CD,TX.VAL.MRCH.XD.WD
0,9896188,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,1717856.0,78.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
1,9896189,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,1717856.0,78.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
2,9896190,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,1717856.0,78.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
3,9896191,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,1717856.0,78.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
4,9896192,0.0,0.0,733391.0,424916.0,391925.0,64.0,-150.0,1717856.0,78.0,...,39.701735,10.447935,1.398441,23.603533,0.908951,2.398344,0.944532,0.138105,1.664240e+12,213.064797
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97179,494713,0.0,0.0,2656156.0,1120500.0,1111402.0,-26.0,121.0,2527013.0,NaN,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97180,494714,0.0,0.0,2656156.0,1120500.0,1111402.0,-26.0,121.0,2527013.0,NaN,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97181,494715,0.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,2527013.0,NaN,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97182,494716,0.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,2527013.0,NaN,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005
97183,494717,0.0,NaN,2656156.0,1120500.0,1111402.0,-26.0,121.0,2527013.0,NaN,...,50.579743,43.125018,0.391859,0.636003,0.412975,5.101246,0.912642,2.018508,2.546920e+11,402.530005

In [31]:
# impute data
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsRegressor
from sklearn import impute
# Exclude the target variable when imputing
num_data_impute = num_data.drop('new_confirmed', axis=1)
imputer = impute.KNNImputer(n_neighbors=3)
imputer = imputer.fit(num_data_impute)
data_imputed = imputer.transform(num_data_impute)

In [32]:
data_imputed = pd.DataFrame(data_imputed,columns = num_data_impute.columns)

In [33]:
# Add the target varibale back
data_imputed['new_confirmed'] = num_data.iloc[:, 0]
# Add the object variables back
data_imputed = pd.concat([data_imputed, no_num], axis=1)

In [34]:
data_imputed.dtypes

Unnamed: 0            float64
new_deceased          float64
population            float64
population_male       float64
population_female     float64
                       ...
subregion1_name        object
iso_3166_1_alpha_2     object
iso_3166_1_alpha_3     object
location_key_y         object
location_key           object
Length: 173, dtype: object

In [35]:
from google.colab import drive
drive.mount('drive')

Mounted at drive

In [36]:
data_imputed.to_csv('top_10_gdp_covid_data_imputed.csv')
!cp top_10_gdp_covid_data_imputed.csv "drive/My Drive/"